-- Phase 16C: document extraction/chunking foundation (additive).
--
-- Hand-authored, NOT generated by `npx prisma migrate dev` — no live
-- database is reachable in this environment, so this migration has not
-- been applied anywhere. Apply it the same way every other migration in
-- this project is applied:
--   development:  npx prisma migrate dev
--   production:   npx prisma migrate deploy

-- AlterTable
ALTER TABLE "Document" ADD COLUMN "lastProcessedAt" TIMESTAMP(3);

-- CreateTable
CREATE TABLE "DocumentTextChunk" (
    "id"          TEXT NOT NULL,
    "documentId"  TEXT NOT NULL,
    "position"    INTEGER NOT NULL,
    "text"        TEXT NOT NULL,
    "charCount"   INTEGER NOT NULL,
    "tokenCount"  INTEGER,
    "contentHash" TEXT,
    "metadata"    JSONB NOT NULL DEFAULT '{}',
    "status"      TEXT NOT NULL DEFAULT 'chunked',
    "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"   TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DocumentTextChunk_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "DocumentTextChunk_documentId_position_key" ON "DocumentTextChunk"("documentId", "position");

-- CreateIndex
CREATE INDEX "DocumentTextChunk_documentId_idx" ON "DocumentTextChunk"("documentId");
