-- Phase 16A: document ingestion foundation (additive; no upload route, no
-- extraction, no embedding wiring yet).
--
-- Hand-authored, NOT generated by `npx prisma migrate dev` — no live
-- database is reachable in this environment, so this migration has not
-- been applied anywhere. Apply it the same way every other migration in
-- this project is applied:
--   development:  npx prisma migrate dev
--   production:   npx prisma migrate deploy
--
-- No relation to "DocumentChunk" is created here — deliberately. See this
-- table's comment in prisma/schema.prisma for why a hard foreign key would
-- break Phase 15's existing Brain<->RAG pgvector write path.

-- CreateTable
CREATE TABLE "Document" (
    "id"               TEXT NOT NULL,
    "title"            TEXT NOT NULL,
    "sourceType"       TEXT NOT NULL,
    "originalFilename" TEXT NOT NULL,
    "mimeType"         TEXT NOT NULL,
    "sizeBytes"        INTEGER NOT NULL,
    "storageProvider"  TEXT NOT NULL DEFAULT 'local',
    "storageKey"       TEXT NOT NULL,
    "extractedTextKey" TEXT,
    "contentHash"      TEXT,
    "metadata"         JSONB NOT NULL DEFAULT '{}',
    "status"           TEXT NOT NULL DEFAULT 'uploaded',
    "error"            TEXT,
    "chunkCount"       INTEGER NOT NULL DEFAULT 0,
    "uploadedBy"       TEXT,
    "tenantId"         TEXT,
    "createdAt"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"        TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Document_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Document_status_idx" ON "Document"("status");

-- CreateIndex
CREATE INDEX "Document_sourceType_idx" ON "Document"("sourceType");
