-- Auto-generated by `prisma migrate dev` (Phase 41.5 hardening).
-- Reconciles naming drift between hand-authored Phase 41 SQL and Prisma conventions,
-- adds missing Phase 37 vector columns, and aligns column types.
-- Vector DDL is wrapped in a conditional DO block so this migration applies
-- cleanly on servers without pgvector.

-- ── FK and index renaming (Phase 41 custom names → Prisma standard names) ────

-- DropForeignKey
ALTER TABLE "IndustrialKnowledgeGraphEdge" DROP CONSTRAINT "IndustrialKnowledgeGraphEdge_org_fk";

-- DropForeignKey
ALTER TABLE "IndustrialKnowledgeGraphEdge" DROP CONSTRAINT "IndustrialKnowledgeGraphEdge_source_fk";

-- DropForeignKey
ALTER TABLE "IndustrialKnowledgeGraphEdge" DROP CONSTRAINT "IndustrialKnowledgeGraphEdge_target_fk";

-- DropForeignKey
ALTER TABLE "IndustrialKnowledgeGraphNode" DROP CONSTRAINT "IndustrialKnowledgeGraphNode_org_fk";

-- DropForeignKey
ALTER TABLE "KnowledgeGraphSnapshot" DROP CONSTRAINT "KnowledgeGraphSnapshot_org_fk";

-- DropForeignKey
ALTER TABLE "TelemetryRecord" DROP CONSTRAINT "TelemetryRecord_organizationId_fkey";

-- ── Column type alignment ─────────────────────────────────────────────────────

-- AlterTable: TIMESTAMPTZ -> TIMESTAMP(3) to match Prisma DateTime mapping
ALTER TABLE "IndustrialKnowledgeGraphEdge" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3);

ALTER TABLE "IndustrialKnowledgeGraphNode"
  ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
  ALTER COLUMN "updatedAt" DROP DEFAULT,
  ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);

ALTER TABLE "KnowledgeGraphSnapshot"
  ALTER COLUMN "createdAt"   SET DATA TYPE TIMESTAMP(3),
  ALTER COLUMN "startedAt"   SET DATA TYPE TIMESTAMP(3),
  ALTER COLUMN "completedAt" SET DATA TYPE TIMESTAMP(3);

ALTER TABLE "OrganizationMember" ALTER COLUMN "updatedAt" DROP DEFAULT;

ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'customer';

-- ── Vector columns (pgvector-conditional) ────────────────────────────────────
-- Gracefully skipped when pgvector is not available (e.g. shadow database,
-- self-managed Postgres without extension). The app degrades safely.

DO $pgvector_migration$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'vector') THEN
    RAISE NOTICE 'pgvector not available -- skipping DocumentChunk and DocumentTextChunk vector columns';
    RETURN;
  END IF;

  -- DocumentTextChunk embedding columns (Phase 16D)
  EXECUTE $$ALTER TABLE "DocumentTextChunk" ADD COLUMN IF NOT EXISTS "embedding"           vector(1536)$$;
  EXECUTE $$ALTER TABLE "DocumentTextChunk" ADD COLUMN IF NOT EXISTS "embeddingModel"       TEXT$$;
  EXECUTE $$ALTER TABLE "DocumentTextChunk" ADD COLUMN IF NOT EXISTS "embeddingDimensions"  INTEGER$$;

  -- DocumentChunk table (Phase 14C)
  EXECUTE $$
    CREATE TABLE IF NOT EXISTS "DocumentChunk" (
        "id"         TEXT NOT NULL,
        "documentId" TEXT NOT NULL,
        "sourceType" TEXT NOT NULL,
        "text"       TEXT NOT NULL,
        "position"   INTEGER NOT NULL,
        "metadata"   JSONB NOT NULL DEFAULT '{}',
        "model"      TEXT NOT NULL,
        "dimensions" INTEGER NOT NULL,
        "embedding"  vector(1536) NOT NULL,
        "createdAt"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt"  TIMESTAMP(3) NOT NULL,
        CONSTRAINT "DocumentChunk_pkey" PRIMARY KEY ("id")
    )
  $$;
  EXECUTE $$CREATE INDEX IF NOT EXISTS "DocumentChunk_documentId_idx" ON "DocumentChunk"("documentId")$$;
  EXECUTE $$CREATE INDEX IF NOT EXISTS "DocumentChunk_sourceType_idx" ON "DocumentChunk"("sourceType")$$;
END $pgvector_migration$;

-- ── AddForeignKey (standard Prisma names) ────────────────────────────────────

ALTER TABLE "TelemetryRecord" ADD CONSTRAINT "TelemetryRecord_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "IndustrialKnowledgeGraphNode" ADD CONSTRAINT "IndustrialKnowledgeGraphNode_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "IndustrialKnowledgeGraphEdge" ADD CONSTRAINT "IndustrialKnowledgeGraphEdge_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "IndustrialKnowledgeGraphEdge" ADD CONSTRAINT "IndustrialKnowledgeGraphEdge_sourceNodeId_fkey" FOREIGN KEY ("sourceNodeId") REFERENCES "IndustrialKnowledgeGraphNode"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "IndustrialKnowledgeGraphEdge" ADD CONSTRAINT "IndustrialKnowledgeGraphEdge_targetNodeId_fkey" FOREIGN KEY ("targetNodeId") REFERENCES "IndustrialKnowledgeGraphNode"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "KnowledgeGraphSnapshot" ADD CONSTRAINT "KnowledgeGraphSnapshot_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ── RenameIndex ───────────────────────────────────────────────────────────────

ALTER INDEX "DigitalTwinRelation_src_tgt_type_key" RENAME TO "DigitalTwinRelation_sourceNodeId_targetNodeId_relationType_key";

ALTER INDEX "IndustrialKnowledgeGraphEdge_org_edgeType_idx"  RENAME TO "IndustrialKnowledgeGraphEdge_organizationId_edgeType_idx";
ALTER INDEX "IndustrialKnowledgeGraphEdge_org_source_idx"    RENAME TO "IndustrialKnowledgeGraphEdge_organizationId_sourceNodeId_idx";
ALTER INDEX "IndustrialKnowledgeGraphEdge_org_target_idx"    RENAME TO "IndustrialKnowledgeGraphEdge_organizationId_targetNodeId_idx";
ALTER INDEX "IndustrialKnowledgeGraphEdge_src_tgt_type_key"  RENAME TO "IndustrialKnowledgeGraphEdge_sourceNodeId_targetNodeId_edge_key";

ALTER INDEX "IndustrialKnowledgeGraphNode_orgId_nodeType_idx"  RENAME TO "IndustrialKnowledgeGraphNode_organizationId_nodeType_idx";
ALTER INDEX "IndustrialKnowledgeGraphNode_org_type_entity_key" RENAME TO "IndustrialKnowledgeGraphNode_organizationId_nodeType_entity_key";

ALTER INDEX "KnowledgeGraphSnapshot_org_createdAt_idx" RENAME TO "KnowledgeGraphSnapshot_organizationId_createdAt_idx";

ALTER INDEX "TelemetryRecord_gatewayId_ts_idx"     RENAME TO "TelemetryRecord_gatewayId_timestamp_idx";
ALTER INDEX "TelemetryRecord_orgId_assetId_ts_idx" RENAME TO "TelemetryRecord_organizationId_assetId_timestamp_idx";
ALTER INDEX "TelemetryRecord_orgId_receivedAt_idx" RENAME TO "TelemetryRecord_organizationId_receivedAt_idx";
ALTER INDEX "TelemetryRecord_orgId_tag_ts_idx"     RENAME TO "TelemetryRecord_organizationId_tag_timestamp_idx";
