-- Phase 14C: RAG persistence layer (additive; not wired into /api/brain).
--
-- Hand-authored, NOT generated by `npx prisma migrate dev` — no live
-- database is reachable in this environment, so this migration has not
-- been applied anywhere. Apply it the same way every other migration in
-- this project is applied:
--   development:  npx prisma migrate dev
--   production:   npx prisma migrate deploy
-- against a Postgres instance with the `vector` extension available.

-- Enable pgvector. Requires the `vector` extension to exist on the
-- Postgres server (Supabase, Neon, RDS 15+, and most managed providers
-- ship it; a self-managed instance may need it installed separately and
-- `CREATE EXTENSION` privilege). If this statement fails, every method in
-- src/lib/rag/vector-store-pgvector.ts still degrades safely to a
-- no-op/empty result rather than crashing the app — see that file's header
-- comment for the full degrade chain.
CREATE EXTENSION IF NOT EXISTS vector;

-- CreateTable
CREATE TABLE "DocumentChunk" (
    "id"         TEXT NOT NULL,
    "documentId" TEXT NOT NULL,
    "sourceType" TEXT NOT NULL,
    "text"       TEXT NOT NULL,
    "position"   INTEGER NOT NULL,
    "metadata"   JSONB NOT NULL DEFAULT '{}',
    "model"      TEXT NOT NULL,
    "dimensions" INTEGER NOT NULL,
    "embedding"  vector(1536) NOT NULL,
    "createdAt"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"  TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DocumentChunk_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "DocumentChunk_documentId_idx" ON "DocumentChunk"("documentId");

-- CreateIndex
CREATE INDEX "DocumentChunk_sourceType_idx" ON "DocumentChunk"("sourceType");

-- CreateIndex: approximate-nearest-neighbor index for the cosine-distance
-- search vector-store-pgvector.ts queries with (the `<=>` operator). HNSW
-- chosen over ivfflat — no training/list-count tuning required, and better
-- recall at the small-to-medium corpus sizes this project is at today.
CREATE INDEX "DocumentChunk_embedding_hnsw_idx" ON "DocumentChunk"
    USING hnsw ("embedding" vector_cosine_ops);
