import type { Citation } from "./rag-types";
import type { GuardrailFlag } from "@/lib/llm/guardrails";
import type { UsageMetadata } from "@/lib/llm/gateway";
import type { ReasoningResult } from "@/lib/industrial/reasoning";
import type { ConfidenceResult } from "@/lib/industrial/confidence";
import type { RootCauseAnalysis } from "@/lib/industrial/root-cause";
import type { RetrievalResult } from "@/lib/retrieval/retrieval-types";
import type { RagSearchResult } from "@/lib/rag/types";

/**
 * Hermes OS — Service Interface Layer
 *
 * The frontend depends ONLY on these interfaces, never on a concrete
 * implementation. In V1 these are backed by mock data and Next.js API
 * routes (the BFF). In Phase 2, the same interfaces are re-pointed at
 * FastAPI microservices (AI Gateway, OPC UA / Modbus TCP / MQTT
 * gateways, Historian, Auth, Audit) with NO frontend changes.
 *
 * Rule: if a component imports from `@/lib/services`, it must import a
 * TYPE or a function from this layer — never reach past it to a route
 * handler or a data source directly.
 */

export type ServiceResult<T> =
  | { ok: true; data: T }
  | { ok: false; error: string };

// --- AI Gateway -----------------------------------------------------------
export interface ChatMessage {
  role: "user" | "assistant" | "system";
  content: string;
}
export interface AiGateway {
  /** Single-turn or multi-turn completion. V1: real LLM via BFF route. */
  chat(messages: ChatMessage[]): Promise<ServiceResult<string>>;
}

// --- Telemetry / Historian ------------------------------------------------
export interface TelemetryPoint {
  tag: string;
  value: number;
  unit: string;
  ts: number;
}
export interface TelemetryService {
  /** Latest dashboard snapshot. V1: simulated. Phase 2: Historian. */
  snapshot(): Promise<ServiceResult<DashboardSnapshot>>;
}

// --- Knowledge Library ----------------------------------------------------
export interface KnowledgeArticle {
  id: string;
  /** message keys under `knowledge.<id>.*` — client translates */
  titleKey: string;
  summaryKey: string;
}
export interface KnowledgeService {
  search(query: string): Promise<ServiceResult<KnowledgeArticle[]>>;
}

// --- Auth -----------------------------------------------------------------
export interface SessionUser {
  id: string;
  name: string;
  role: "operator" | "engineer" | "admin";
}
export interface AuthService {
  currentUser(): Promise<ServiceResult<SessionUser | null>>;
}

// --- Industrial Connectors (OPC UA / Modbus TCP / MQTT) -------------------
export type ConnectorKind = "opcua" | "modbus-tcp" | "mqtt";
export interface ConnectorStatus {
  kind: ConnectorKind;
  name: string;
  connected: boolean;
}
export interface IndustrialConnectors {
  list(): Promise<ServiceResult<ConnectorStatus[]>>;
}

// --- Dashboard snapshot (Step 3) -------------------------------------------
// Returned by TelemetryService. V1: generated by src/lib/industrial/simulator.
// Phase 2: assembled by the Historian + telemetry engine. Text fields are
// message KEYS, not strings — the client translates, so FA/EN stays complete.

export type LineStatus = "running" | "idle" | "fault";
export type DeviceStatus = "online" | "offline" | "fault";
export type HealthStatus = "ok" | "warning" | "degraded";
export type Severity = "critical" | "high" | "medium" | "low";

export interface MetricSeries {
  tag: string;          // machine identifier, e.g. "TT-101"
  value: number;
  unit: string;         // SI unit symbol, e.g. "°C"
  min: number;
  max: number;
  history: number[];    // recent window, oldest -> newest
}

export interface DashboardSnapshot {
  ts: number;
  overview: {
    oee: number; availability: number; performance: number; quality: number;
    activeLines: number; totalLines: number;
  };
  lines: { id: string; status: LineStatus; throughput: number; target: number }[];
  plc: { id: string; model: string; status: DeviceStatus; cycleMs: number }[];
  scada: {
    servers: { id: string; status: DeviceStatus; latencyMs: number }[];
    tagsPolled: number; updateRateMs: number;
  };
  network: {
    devices: number; online: number; blockedEvents: number; ids: HealthStatus;
  };
  alarms: {
    counts: Record<Severity, number>;
    recent: { id: string; severity: Severity; msgKey: string; ts: number }[];
  };
  temperature: MetricSeries[];
  pressure: MetricSeries[];
  flow: MetricSeries[];
  energy: { nowKw: number; todayKwh: number; peakKw: number; history: number[] };
  ai: { id: string; recKey: string; confidence: number }[];
  maintenance: { id: string; assetKey: string; priority: number; dueDays: number; severity: Severity }[];
  risk: {
    score: number;            // 0-100, lower is better
    trend: "up" | "down" | "flat";
    factors: { key: string; weight: number }[];
  };
}

// --- Hermes Brain (Step 4) --------------------------------------------------
export type BrainDomainId =
  | "plc" | "scada" | "hmi" | "electrical" | "sensors" | "digitalIo"
  | "analogIo" | "drives" | "motors" | "otNetwork" | "cybersecurity"
  | "maintenance";

export type SafetyKind = "electrical" | "mechanical" | "general";

/** How the answer was produced. "future-rag" is reserved for Phase 2
 *  retrieval-augmented generation; no V1 code path emits it yet. */
export type ReasoningMode = "library" | "llm" | "future-rag";

export interface BrainAnalysis {
  mode: ReasoningMode;
  domains: { id: BrainDomainId; score: number }[];
  libraries: string[];           // knowledge library ids used
  /** evidence references; in V1 these point at library content via
   *  message keys, so the UI renders them bilingually */
  citations: Citation[];
  confidence: number;            // 0..1, capped — never presented as certainty
  safety: SafetyKind;
  /** set when a guardrail intercepted the question (e.g. safety bypass) */
  guardrail?: GuardrailFlag;
  /** present only when mode === "llm"; localized free text from the gateway */
  llm?: { summary: string; cause: string; analysis: string[]; checks: string[] };
  /** gateway usage metadata, present when a provider was invoked */
  usage?: UsageMetadata;
  /* ---- Step 6 additive fields (optional; V1 UI intentionally ignores) ---- */
  /** detected vendor context, most relevant first */
  vendors?: string[];
  /** deterministic risk classification from the reasoning pipeline */
  riskLevel?: "low" | "medium" | "high" | "unknown";
  /** learning metadata: evidence strength + matched engineering cases */
  evidence?: {
    score: number;
    caseMatches: string[];
    /** Step 7 additive detail for UI display */
    cases?: { id: string; vendor: string; category: BrainDomainId }[];
  };
  /** reasoning pipeline trace (stage timings) */
  pipeline?: { steps: { id: string; ms: number }[] };
  /** Step 8A: deterministic engineering reasoning (no LLM involvement) */
  reasoning?: ReasoningResult;
  /* ---- Step 8B: Industrial Copilot Report (optional, additive) ---- */
  /** localized probable causes from the deterministic reasoning engine */
  probableCauses?: string[];
  /** localized recommended actions from the deterministic reasoning engine */
  recommendedActions?: string[];
  /** localized one-line synthesis of the evidence basis */
  evidenceSummary?: string;
  /** always true by design — Hermes Brain never acts on real equipment */
  humanApprovalRequired?: true;
  /** Step 8C: deterministic 0-100 confidence with band classification */
  confidenceReport?: ConfidenceResult;
  /** Step 8: case-driven root cause analysis; present only when an
   *  engineering case matched. Re-exported for API consumers. */
  rootCause?: RootCauseAnalysis;
  /** Phase 10: hybrid retrieval — ranked evidence + derived confidence band */
  retrieval?: RetrievalResult;
  /** Unknown layer: evidence was insufficient for any classification.
   *  Domains/libraries/citations are empty and retrieval was disabled. */
  unknown?: true;
  /** Phase 13: optional AI Provider Router enhancement layer, attached only
   *  when HERMES_AI_ROUTER_ENABLED=true and the question wasn't guardrail-
   *  flagged. Purely additive — every field above this one is produced by
   *  the deterministic pipeline and is never altered by this block. Absent
   *  entirely when the flag is off (default) or the question is unknown. */
  aiEnhancement?: AIEnhancement;
  /** Phase 15: optional RAG evidence layer, attached only when
   *  HERMES_RAG_BRAIN_ENABLED=true and the question wasn't guardrail-
   *  flagged. Purely additive — never alters `retrieval` or any other
   *  field above. Absent entirely when the flag is off (default) or the
   *  question is unknown. */
  ragEvidence?: RagEvidence;
  /** Phase 17D: optional document-pipeline semantic search layer, attached
   *  only when HERMES_DOCUMENT_RAG_ENABLED=true and the question wasn't
   *  guardrail-flagged. Purely additive — a second, independent evidence
   *  layer alongside `ragEvidence` (which embeds engineering-case and
   *  knowledge-library text on the fly). Absent entirely when the flag is
   *  off (default) or the question is unknown. */
  documentRagEvidence?: DocumentRagEvidence;
  /** Phase 18D: optional engineering-memory evidence layer, attached only when
   *  HERMES_MEMORY_RAG_ENABLED=true and the question wasn't guardrail-flagged.
   *  Surfaces past similar analyses with learning-adjusted scores (Phase 18C).
   *  Purely additive — never alters any field above. Absent entirely when the
   *  flag is off (default) or the question is unknown. */
  memoryEvidence?: MemoryEvidence;
  /** Phase 19C: optional project reasoning context, attached only when
   *  HERMES_PROJECT_INTELLIGENCE_ENABLED=true, a valid projectId was supplied,
   *  and the project was found. Provides project metadata to the Brain response
   *  so callers can display project-aware context alongside the analysis.
   *  Purely additive — never alters any field above. Absent when the flag is
   *  off (default), no projectId given, project not found, or guardrail hit. */
  projectContext?: ProjectContext;
}

/** Phase 13: the shape `/api/brain` attaches to `BrainAnalysis.aiEnhancement`. */
export interface AIEnhancement {
  enabled: boolean;
  /** the concrete provider that produced `content` — "none" when the call
   *  could not be completed at all (caught at the route level) */
  provider: string;
  /** the AI Provider Router's active mode for this call: mock | real | hybrid */
  mode: string;
  /** the enhancement text itself — never a raw error message or stack trace */
  content: string;
  confidence?: number;
  /** true whenever `content` came from a mock/degraded path rather than a
   *  genuine real-provider completion (missing key, missing SDK, timeout,
   *  provider error, or forced mock mode) */
  fallbackUsed: boolean;
}

/** Phase 15: the shape `/api/brain` attaches to `BrainAnalysis.ragEvidence`.
 *  Embedding/vector-store evidence on top of the existing (keyword)
 *  `retrieval` field — never a replacement for it. */
export interface RagEvidence {
  enabled: boolean;
  /** the RAG pipeline's active mode for this call: mock | pgvector | external */
  mode: string;
  /** chunk + cosine-similarity score pairs — empty when RAG found nothing
   *  or degraded; never absent (always an array, even when empty) */
  results: RagSearchResult[];
  /** true whenever this evidence came from a degraded/disabled path rather
   *  than a genuine RAG pass — RAG pipeline disabled internally
   *  (HERMES_RAG_ENABLED=false), or any pipeline-level error */
  fallbackUsed: boolean;
  /** present only when something degraded — a safe, enumerated code
   *  (e.g. "pipeline_error", "rag_pipeline_error"), never a raw provider/
   *  vector-store error message or stack trace */
  error?: string;
}

/** Phase 17D: the shape `/api/brain` attaches to
 *  `BrainAnalysis.documentRagEvidence`. Semantic search over the document
 *  pipeline index — indexed via `DocumentTextChunk.embedding` (pgvector or
 *  session-mode in-process buffer). Independent of `ragEvidence`, which
 *  embeds engineering-case/knowledge-library text per-request. */
export interface DocumentRagEvidence {
  enabled: boolean;
  /** top matching document chunks from the document pipeline index — empty
   *  when the store has no indexed chunks yet, or when embedding/search
   *  degraded; never absent (always an array, even when empty) */
  matches: {
    chunkId: string;
    documentId: string;
    position: number;
    text: string;
    score: number;
  }[];
  /** true when the search couldn't run at all (unexpected exception) rather
   *  than when it ran normally but returned 0 results */
  fallbackUsed: boolean;
  /** present only when something degraded — a safe, enumerated code, never
   *  a raw error message or stack trace */
  error?: string;
}

/** Phase 19C: project metadata injected into the Brain analysis when a project
 *  is found for the given projectId and the project-intelligence flag is on. */
export interface ProjectContext {
  projectId: string;
  projectName: string;
  description: string;
  status: string;
  /** Number of EngineeringMemory records tagged with this project. */
  relatedMemoriesCount: number;
}

/** Phase 18D: a single ranked engineering-memory match with its learning score. */
export interface MemoryEvidenceMatch {
  id: string;
  /** the original question this memory was created from */
  query: string;
  domain: string;
  /** analysisSummary — what the past analysis concluded */
  summary: string;
  /** stored confidence 0–100 */
  confidence: number;
  /** feedback-mirrored outcome of the past analysis */
  outcome: "unknown" | "success" | "partial" | "failed";
  /** 0–100, learning-adjusted score from Phase 18C feedback weighting */
  score: number;
  /** scoring reason codes — e.g. "domain_match", "keyword_overlap", "feedback_success" */
  reasons: string[];
}

/** Phase 18D: the shape `/api/brain` attaches to `BrainAnalysis.memoryEvidence`.
 *  Retrieval-based evidence from past engineering analyses — independent of both
 *  `ragEvidence` (per-request embedding) and `documentRagEvidence` (document chunks). */
export interface MemoryEvidence {
  enabled: boolean;
  /** Top matching past analyses, learning-score sorted descending.
   *  Always an array (empty when store is empty or retrieval degraded). */
  matches: MemoryEvidenceMatch[];
  /** true when retrieval threw unexpectedly — NOT when it ran and returned 0 results */
  fallbackUsed: boolean;
  /** present only when degraded — safe enumerated code, never raw error/stack */
  error?: string;
}

/** Step 8: Knowledge Cloud browser payload (full metadata, key-based text). */
export interface KnowledgeBrowseData {
  libraries: {
    id: string;
    category: string;
    domains: BrainDomainId[];
    keywords: string[];
    vendor?: string;
    futureEmbeddingReady: boolean;
    /** message-catalog keys — present for the static JSON corpus only */
    titleKey?: string;
    summaryKey?: string;
    /** Phase 11B-B: literal text, present only for PostgreSQL-published
     *  articles (which carry their own copy, not a message-catalog key) */
    title?: string;
    summary?: string;
  }[];
  cases: {
    id: string;
    vendor: string;
    domain: BrainDomainId;
    keywords: string[];
    /** Phase 11B-B: literal text, present only for PostgreSQL-published
     *  cases (which carry their own copy, not a message-catalog key) */
    title?: string;
    summary?: string;
  }[];
}

export interface BrainMemoryStats {
  count: number;
  /** Unknown layer: classified analyses */
  knownCount: number;
  /** Unknown layer: analyses stored as Unknown */
  unknownCount: number;
  avgConfidence: number;
  avgEvidence: number;
  byDomain: Record<string, number>;
  /** Phase A: top vendors aggregated from known analyses (session-scoped) */
  byVendor: Record<string, number>;
  /** Step 9: per-library Brain reference counts (session-scoped) */
  libraryRefs: Record<string, number>;
  guardrailHits: number;
}

export interface BrainService {
  analyze(question: string, locale: string): Promise<ServiceResult<BrainAnalysis>>;
  /** Step 7: aggregate stats from the Analysis Memory Engine (GET /api/brain).
   *  Step 9: also returns recentLibraries — distinct libraries cited by the
   *  most recent analyses, newest first. */
  memory(
    n?: number
  ): Promise<ServiceResult<{ stats: BrainMemoryStats; recentLibraries: string[] }>>;
}
