import type { Citation } from "./rag-types";
import type { GuardrailFlag } from "@/lib/llm/guardrails";
import type { UsageMetadata } from "@/lib/llm/gateway";
import type { ReasoningResult } from "@/lib/industrial/reasoning";
import type { ConfidenceResult } from "@/lib/industrial/confidence";
import type { RootCauseAnalysis } from "@/lib/industrial/root-cause";

/**
 * Hermes OS — Service Interface Layer
 *
 * The frontend depends ONLY on these interfaces, never on a concrete
 * implementation. In V1 these are backed by mock data and Next.js API
 * routes (the BFF). In Phase 2, the same interfaces are re-pointed at
 * FastAPI microservices (AI Gateway, OPC UA / Modbus TCP / MQTT
 * gateways, Historian, Auth, Audit) with NO frontend changes.
 *
 * Rule: if a component imports from `@/lib/services`, it must import a
 * TYPE or a function from this layer — never reach past it to a route
 * handler or a data source directly.
 */

export type ServiceResult<T> =
  | { ok: true; data: T }
  | { ok: false; error: string };

// --- AI Gateway -----------------------------------------------------------
export interface ChatMessage {
  role: "user" | "assistant" | "system";
  content: string;
}
export interface AiGateway {
  /** Single-turn or multi-turn completion. V1: real LLM via BFF route. */
  chat(messages: ChatMessage[]): Promise<ServiceResult<string>>;
}

// --- Telemetry / Historian ------------------------------------------------
export interface TelemetryPoint {
  tag: string;
  value: number;
  unit: string;
  ts: number;
}
export interface TelemetryService {
  /** Latest dashboard snapshot. V1: simulated. Phase 2: Historian. */
  snapshot(): Promise<ServiceResult<DashboardSnapshot>>;
}

// --- Knowledge Library ----------------------------------------------------
export interface KnowledgeArticle {
  id: string;
  /** message keys under `knowledge.<id>.*` — client translates */
  titleKey: string;
  summaryKey: string;
}
export interface KnowledgeService {
  search(query: string): Promise<ServiceResult<KnowledgeArticle[]>>;
}

// --- Auth -----------------------------------------------------------------
export interface SessionUser {
  id: string;
  name: string;
  role: "operator" | "engineer" | "admin";
}
export interface AuthService {
  currentUser(): Promise<ServiceResult<SessionUser | null>>;
}

// --- Industrial Connectors (OPC UA / Modbus TCP / MQTT) -------------------
export type ConnectorKind = "opcua" | "modbus-tcp" | "mqtt";
export interface ConnectorStatus {
  kind: ConnectorKind;
  name: string;
  connected: boolean;
}
export interface IndustrialConnectors {
  list(): Promise<ServiceResult<ConnectorStatus[]>>;
}

// --- Dashboard snapshot (Step 3) -------------------------------------------
// Returned by TelemetryService. V1: generated by src/lib/industrial/simulator.
// Phase 2: assembled by the Historian + telemetry engine. Text fields are
// message KEYS, not strings — the client translates, so FA/EN stays complete.

export type LineStatus = "running" | "idle" | "fault";
export type DeviceStatus = "online" | "offline" | "fault";
export type HealthStatus = "ok" | "warning" | "degraded";
export type Severity = "critical" | "high" | "medium" | "low";

export interface MetricSeries {
  tag: string;          // machine identifier, e.g. "TT-101"
  value: number;
  unit: string;         // SI unit symbol, e.g. "°C"
  min: number;
  max: number;
  history: number[];    // recent window, oldest -> newest
}

export interface DashboardSnapshot {
  ts: number;
  overview: {
    oee: number; availability: number; performance: number; quality: number;
    activeLines: number; totalLines: number;
  };
  lines: { id: string; status: LineStatus; throughput: number; target: number }[];
  plc: { id: string; model: string; status: DeviceStatus; cycleMs: number }[];
  scada: {
    servers: { id: string; status: DeviceStatus; latencyMs: number }[];
    tagsPolled: number; updateRateMs: number;
  };
  network: {
    devices: number; online: number; blockedEvents: number; ids: HealthStatus;
  };
  alarms: {
    counts: Record<Severity, number>;
    recent: { id: string; severity: Severity; msgKey: string; ts: number }[];
  };
  temperature: MetricSeries[];
  pressure: MetricSeries[];
  flow: MetricSeries[];
  energy: { nowKw: number; todayKwh: number; peakKw: number; history: number[] };
  ai: { id: string; recKey: string; confidence: number }[];
  maintenance: { id: string; assetKey: string; priority: number; dueDays: number; severity: Severity }[];
  risk: {
    score: number;            // 0-100, lower is better
    trend: "up" | "down" | "flat";
    factors: { key: string; weight: number }[];
  };
}

// --- Hermes Brain (Step 4) --------------------------------------------------
export type BrainDomainId =
  | "plc" | "scada" | "hmi" | "electrical" | "sensors" | "digitalIo"
  | "analogIo" | "drives" | "motors" | "otNetwork" | "cybersecurity"
  | "maintenance";

export type SafetyKind = "electrical" | "mechanical" | "general";

/** How the answer was produced. "future-rag" is reserved for Phase 2
 *  retrieval-augmented generation; no V1 code path emits it yet. */
export type ReasoningMode = "library" | "llm" | "future-rag";

export interface BrainAnalysis {
  mode: ReasoningMode;
  domains: { id: BrainDomainId; score: number }[];
  libraries: string[];           // knowledge library ids used
  /** evidence references; in V1 these point at library content via
   *  message keys, so the UI renders them bilingually */
  citations: Citation[];
  confidence: number;            // 0..1, capped — never presented as certainty
  safety: SafetyKind;
  /** set when a guardrail intercepted the question (e.g. safety bypass) */
  guardrail?: GuardrailFlag;
  /** present only when mode === "llm"; localized free text from the gateway */
  llm?: { summary: string; cause: string; analysis: string[]; checks: string[] };
  /** gateway usage metadata, present when a provider was invoked */
  usage?: UsageMetadata;
  /* ---- Step 6 additive fields (optional; V1 UI intentionally ignores) ---- */
  /** detected vendor context, most relevant first */
  vendors?: string[];
  /** deterministic risk classification from the reasoning pipeline */
  riskLevel?: "low" | "medium" | "high" | "unknown";
  /** learning metadata: evidence strength + matched engineering cases */
  evidence?: {
    score: number;
    caseMatches: string[];
    /** Step 7 additive detail for UI display */
    cases?: { id: string; vendor: string; category: BrainDomainId }[];
  };
  /** reasoning pipeline trace (stage timings) */
  pipeline?: { steps: { id: string; ms: number }[] };
  /** Step 8A: deterministic engineering reasoning (no LLM involvement) */
  reasoning?: ReasoningResult;
  /* ---- Step 8B: Industrial Copilot Report (optional, additive) ---- */
  /** localized probable causes from the deterministic reasoning engine */
  probableCauses?: string[];
  /** localized recommended actions from the deterministic reasoning engine */
  recommendedActions?: string[];
  /** localized one-line synthesis of the evidence basis */
  evidenceSummary?: string;
  /** always true by design — Hermes Brain never acts on real equipment */
  humanApprovalRequired?: true;
  /** Step 8C: deterministic 0-100 confidence with band classification */
  confidenceReport?: ConfidenceResult;
  /** Step 8: case-driven root cause analysis; present only when an
   *  engineering case matched. Re-exported for API consumers. */
  rootCause?: RootCauseAnalysis;
  /** Unknown layer: evidence was insufficient for any classification.
   *  Domains/libraries/citations are empty and retrieval was disabled. */
  unknown?: true;
}

/** Step 8: Knowledge Cloud browser payload (full metadata, key-based text). */
export interface KnowledgeBrowseData {
  libraries: {
    id: string;
    category: string;
    domains: BrainDomainId[];
    keywords: string[];
    vendor?: string;
    futureEmbeddingReady: boolean;
    titleKey: string;
    summaryKey: string;
  }[];
  cases: {
    id: string;
    vendor: string;
    domain: BrainDomainId;
    keywords: string[];
  }[];
}

export interface BrainMemoryStats {
  count: number;
  /** Unknown layer: classified analyses */
  knownCount: number;
  /** Unknown layer: analyses stored as Unknown */
  unknownCount: number;
  avgConfidence: number;
  avgEvidence: number;
  byDomain: Record<string, number>;
  /** Phase A: top vendors aggregated from known analyses (session-scoped) */
  byVendor: Record<string, number>;
  /** Step 9: per-library Brain reference counts (session-scoped) */
  libraryRefs: Record<string, number>;
  guardrailHits: number;
}

export interface BrainService {
  analyze(question: string, locale: string): Promise<ServiceResult<BrainAnalysis>>;
  /** Step 7: aggregate stats from the Analysis Memory Engine (GET /api/brain).
   *  Step 9: also returns recentLibraries — distinct libraries cited by the
   *  most recent analyses, newest first. */
  memory(
    n?: number
  ): Promise<ServiceResult<{ stats: BrainMemoryStats; recentLibraries: string[] }>>;
}
